### DISCUSSION TITLE
ERROR: Python dependency not found (on Windows)

### DISCUSSION THREAD

**Discussion by scott-guthridge** [mesonbuild/meson-python#558] [Q&A] [answered]
We're trying to build a wheel for a Cython project through github workflows on Windows.  The build is failing pretty early on.  The question spans github actions,  cibuildwheel, and meson-python -- hopefully, it's not off-topic here.

Top level meson.build begins with:

```
project('libvna', 'cython',
  version: '0.0.5-13',
  license: 'GPL-3',
  default_options: [
    'buildtype=debugoptimized',
    'b_ndebug=if-release',
    'c_std=c99',
  ],
)

py_mod = import('python')
py3 = py_mod.find_installation(pure: false)
dep_py = py3.dependency()                                               <----- line 13 FAILING HERE
dep_vna = dependency('libvna', version: '>=0.3.9')

srcdir = meson.source_root()
testdir = join_paths(srcdir, 'tests')
builddir = meson.current_build_dir()
```

Here's the error:

```
The Meson build system
Version: 1.3.1
Source dir: D:\a\pylibvna-cicdtest\pylibvna-cicdtest
Build dir: D:\a\pylibvna-cicdtest\pylibvna-cicdtest\.mesonpy-mc6o1dxn
Build type: native build
Project name: libvna
Project version: 0.0.5-13
Cython compiler for the host machine: cython (cython 3.0.7)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-wcok67kg\cp310-win_amd64\build\venv\Scripts\python.exe)
Run-time dependency python found: NO
..\meson.build:13:13: ERROR: Python dependency not found
```

We're following the example of SciPy pretty closely.  Our project is simpler (no Fortran or C++), but we don't see what we're doing differently in this area.

Here's part of the github workflows script:

```yaml
yaml
jobs:
  build_wheels:
    name: Build wheel for ${{matrix.python[0]}}-${{matrix.buildplat[1]}} ${{matrix.buildplat[2]}}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        buildplat:
        # - [ubuntu-22.04, manylinux, x86_64]
        # - [macos-11, macosx, x86_64]
        - [windows-2019, win, AMD64]
        python:
        # - ["cp38",  "3.8"]
        # - ["cp39",  "3.9"]
        - ["cp310", "3.10"]
        # - ["cp311", "3.11"]
        # - ["cp312", "3.12"]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Rtools (Windows)
      # Rtools provides pkg-config on Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install rtools -y --no-progress --force --version=4.0.0.20220206
        echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

    - name: Install cibuildwheel and twine
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel twine

    - name: Install Libvna (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        python3 .github/tools/download-libvna-windows
        New-Item -Path C:\opt -ItemType Directory -Force
        Expand-Archive -Path libvna-windows-x86_64.zip -DestinationPath C:\opt
        echo 'C:\opt\libvna-windows-x86_64\bin;' >> $env:GITHUB_PATH
        Write-Host "GITHUB_PATH=$env:GITHUB_PATH"

    - name: Build Wheels
      env:
        CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}*
        CIBW_ARCHS: ${{ matrix.buildplat[2] }}
        CIBW_ENVIRONMENT: "PIP_NO_BUILD_ISOLATION=false PIP_PRE=1"
        CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS
        CIBW_PRERELEASE_PYTHONS: True
        CIBW_BEFORE_BUILD_LINUX: |
          echo "WHOAMI=`whoami`"
          echo "UNAME=`uname -a`"
          set -e
          yum install -y gcc libyaml-devel
          pip install requests
          python3 .github/tools/install-libvna-rpm
        CIBW_ENVIRONMENT_WINDOWS: >
          PKG_CONFIG_PATH=c:/opt/libvna-windows-x86_64/lib/pkgconfig
          PIP_PRE=1
          PIP_NO_BUILD_ISOLATION=false
        CIBW_BEFORE_BUILD_WINDOWS:
          pip install numpy>=2.0.0.dev0 meson-python cython!=3.0.3 ninja &&
          bash {project}/tools/test-script &&
          powershell -Command "Write-Host GITHUB_PATH=$env:GITHUB_PATH"
        CIBW_BEFORE_BUILD_MACOS: |
          pip install numpy>=2.0.0.dev0 meson-python cython!=3.0.3 ninja
          brew tap scott-guthridge/extra
          brew install scott-guthridge/extra/libvna
      run: python -m cibuildwheel --output-dir wheelhouse
```

Linux and MacOs builds are running without errors.

**Comment by dnicolodi** [comment]
The only thing that stands out as possibly causing the issue is setting `PKG_CONFIG_PATH`. Can you try to do not set this environment variable ans see if the build goes past this point? Other than that, we would need the Meson build log to see what exactly goes wrong.

Other than that, why are you setting the `PIP_NO_BUILD_ISOLATION=false` environment variable? This should be the default. And if you do this, why are you installing numpy, meson-python, cython, and ninja? These would need to be installed again in the build environment anyhow.

**Reply by rgommers** [reply]
I don't see it either. On Windows I'd expect the detection to go via the `python-config` script rather than `pkg-config`, so probably `PKG_CONFIG_PATH` doesn't do anything either way.

The answer will be in `meson-logs/meson-log.txt` in the build directory, which can be obtained with something like this step in your GitHub Actions workflow file:
```yaml
- name: Meson Log
  shell: bash
  if: always()  # or failure()
  run: |
    cat build/meson-logs/meson-log.txt
```

Extra complication: you have to convince `cibuildwheel` to build in a fixed build dir so that the log isn't cleaned up before you can get to it in this debug step. See at the bottom of https://github.com/mesonbuild/meson-python/issues/246 for how.

In the `meson-log.txt` content, you should see content like:
```
Program python3 found: YES (/Users/rgommers/mambaforge/envs/scipy-dev/bin/python3.10)
Searching for 'python-3.10' via pkgconfig lookup in LIBPC
Pkg-config binary for 1 is not cached.
...
```
which will tell you how Meson is searching for `Python.h` & co.
