### ISSUE TITLE
Document setting limited-api via build option better

### ISSUE THREAD

**Issue by lpsinger** [mesonbuild/meson-python#624]
The [`limited-api` option](https://meson-python.readthedocs.io/en/latest/reference/pyproject-settings.html#cmdoption-arg-tool.meson-python.limited-api) can only be set through pyproject.toml, not through the [build config settings](https://meson-python.readthedocs.io/en/latest/reference/config-settings.html) that you can provide on the command line to `pip` or `python -m build`.

Would you please consider supporting `limited-api` as a build config setting? I am using cibuildwheel to build a package that uses the limited API, but my build fails when it tries to install the build package and run my tests under pypy with the following error:

```
  ERROR: hpx-0.0.1-pp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

I would like to be able to customize the build so that it sets `limited-api` to false for PyPy, but I can't do this because `limited-api` is not a build config setting. Here's what I would like to do:

```toml
[tool.cibuildwheel]
config-settings.limited-api = true

# PyPy does not support the Python limited API.
[[tool.cibuildwheel.overrides]]
select = "pp*"
config-settings.limited-api = false
```
