### ISSUE TITLE
bytecode compilation flag doesn't do anything

### ISSUE THREAD

**Issue by peekxc** [mesonbuild/meson-python#706]
As far as I can tell, meson-python doesn't support [bytecode compilation](https://mesonbuild.com/Release-notes-for-1-2-0.html#python-module-can-now-compile-bytecode) of python modules. 

In a simple [test package](https://github.com/peekxc/scikit-package), I tried adding [the bytecompile flag](https://mesonbuild.com/Builtin-options.html#python-module) via pyproject.toml:

```toml
# pyproject.toml
[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'wheel', 'ninja', 'numpy']

...

[tool.meson-python.args]
setup = ['-Dpython.bytecompile=2']
```

Then I tried building the wheel with `build` via `python -m build -nx -v`, which does display the option as set during the build step: 

```
skpackage 0.0.2

  User defined options
    Native files      : /private/var/folders/0l/b3dbb2_d2bb4y3wbbfk0wt_80000gn/T/build-via-sdist-a0tojhrv/skpackage-0.0.2/.mesonpy-9u1xqvsd/meson-python-native-file.ini
    buildtype         : release
    default_library   : static
    python.bytecompile: 2
    b_ndebug          : if-release
    b_vscrt           : md
```

However, when I unpack the corresponding wheel, there's no __pycache__ directory or *.pyc files in sight. Incidentally, when I _install_ the wheel into e.g. a virtualenv, I notice that bytecode files  are there:

```bash
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-311.pyc
│   └── __version__.cpython-311.pyc
└── __version__.py
```

Does this behavior sound normal? I would've thought specifying the byte-compilation flag would make meson add them directly to the wheel, but this doesn't seem to be the case
